<template>
    <div>
        <v-btn>
            INICIO
        </v-btn>
        <v-btn>
            RIFAS
        </v-btn>
        <v-btn>
            GANADORES
        </v-btn>
        <v-btn>
            NOSOTROS
        </v-btn>
        <v-btn>
            CONTACTOS
        </v-btn>
    </div>
</template>